baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme="learn"

[outputs]
  home = ["HTML", "RSS"]


  [Language]
    [Language.es]
    title="Español"
    weight= 1
    ContentDir="content/es"

    [Language.en]
    title="Ingles"
    weight= 2
    ContentDir="content/fr"

    